CE103 Algorithms and Programming I HW4: ce103_hw4_cs_dll.Class2 Class Reference
ce103_hw4_cs_dll.Class2 Class Reference
Public Member Functions
static int ce103_fibonacciNumber_cpp (int fiIndex)
static IntPtr ce103_strrev_cpp (char[] fiStr)
static int ce103_strlen_cpp (string fiStr)
static IntPtr ce103_strcat_cpp (char[] fiDest, char[] fiSrc)
static int ce103_strcmp_cpp (string fiLhs, string fiRhs)
static IntPtr ce103_strcpy_cpp (char[] foDestination, char[] fiSource)
static void ce103_hex2bin_cpp (string fiHex, int fiHexLen, byte[] foBin)
static void ce103_bin2hex_cpp ([In] byte[] fiBin, int fiBinLen, [Out] char[] foHex)
strrev (ce103_strrev_cs_imported)
Reverse string
Reverse given string
Parameters
[in] fiStr [string] The given string which is needed to be reversed.
Return values
[
b string] ce103_strrev_cpp
string ce103_strrev_cs_imported (string fiStr)
strlen (ce103_strlen_cs_imported)
Get string length
Get length of a string
Returns the length of the C sharp string str.
Parameters
[in] fiStr [string] given string
Return values
[
b int] ce103_strlen_cpp
int ce103_strlen_cs_imported (string fiStr)
strcat (ce103_strcat_cs_imported)
Concatenate strings
Concatenate two strings
Parameters
[in] fiDest [string] will be appended string
[in] fiSrc [string] will be copy from this
Return values
[
b string] ce103_strcat_cpp
string ce103_strcat_cs_imported (string fiDest, string fiSrc)
strcmp (ce103_strcmp_cs_imported)
Compare two strings
Compare two strings
Parameters
[in] fiLhs [string] string to compare
[in] fiRhs [string] string to compare
Return values
[
b int] ce103_strcmp_cpp
int ce103_strcmp_cs_imported (string fiLhs, string fiRhs)
strcpy (ce103_strcpy_cs_imported)
Copy string
Copy string to another
Parameters
[out] foDestination [string] destination string to copy
[in] fiSource [string] C sharp string to be copied.
Return values
[
b string] ce103_strcpy_cpp
string ce103_strcpy_cs_imported (string foDestination, string fiSource)
hex2bin (ce103_hex2bin_cs_imported)
Hexadecimal string to byte array Conversion
Convert hex string to byte array
Parameters
[in] fiHex [string] Ascii hex string.
[in] fiHexLen [int] Ascii data length.
[out] foBin [byte[]] Convertion result as binary.
void ce103_hex2bin_cs_imported (string fiHex, int fiHexLen, byte[] foBin)
bin2hex (ce103_bin2hex_cs_imported)
Binary to Hexadecimal Conversion
Unpacks alpha numeric value, Example: 0x12 0x34 = "1234".
Parameters
[in] fiBin [byte[]] Binary data to be converted.
[in] fiBinLen [int] Binary data length.
[out] foHex [char[]] Convertion result as ascii. Doubles the binary length.
void ce103_bin2hex_cs_imported ([In] byte[] fiBin, int fiBinLen, [Out] char[] foHex)
fibonacciNumber (ce103_fibonacciNumber_cs_imported)
Fibonacci Number Calculator
Calculates the fibonacci number in the given index and return as output
Parameters
[in] fiIndex [int] index of fibonacci number in the serie
Return values
[
b int] ce103_fibonacciNumber_cpp
int ce103_fibonacciNumber_cs_imported (int fiIndex)
static string PtrToStringUtf8 (IntPtr tr)
Member Function Documentation
ce103_bin2hex_cpp()
static void ce103_hw4_cs_dll.Class2.ce103_bin2hex_cpp ([In] byte[] fiBin, int fiBinLen, [Out] char[] foHex)
Referenced by ce103_hw4_cs_dll.Class2.ce103_bin2hex_cs_imported().
ce103_bin2hex_cs_imported()
void ce103_hw4_cs_dll.Class2.ce103_bin2hex_cs_imported ([In] byte[] fiBin, int fiBinLen, [Out] char[] foHex) inline
References ce103_hw4_cs_dll.Class2.ce103_bin2hex_cpp(), fiBinLen, and foHex.
Referenced by ce103_hw4_test.UnitTest1.ce103_bin2hex_imported_test1(), ce103_hw4_test.UnitTest1.ce103_bin2hex_imported_test2(), ce103_hw4_test.UnitTest1.ce103_bin2hex_imported_test3(), ce103_hw4_test.UnitTest1.ce103_bin2hex_importedcppcs_test1(), ce103_hw4_test.UnitTest1.ce103_bin2hex_importedcppcs_test2(), and ce103_hw4_test.UnitTest1.ce103_bin2hex_importedcppcs_test3().
ce103_fibonacciNumber_cpp()
static int ce103_hw4_cs_dll.Class2.ce103_fibonacciNumber_cpp (int fiIndex)
Referenced by ce103_hw4_cs_dll.Class2.ce103_fibonacciNumber_cs_imported().
ce103_fibonacciNumber_cs_imported()
int ce103_hw4_cs_dll.Class2.ce103_fibonacciNumber_cs_imported (int fiIndex) inline
References ce103_hw4_cs_dll.Class2.ce103_fibonacciNumber_cpp().
Referenced by ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_cs_imported_test_1(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_cs_imported_test_2(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_cs_imported_test_3(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_importedcppcs_test_3().
ce103_hex2bin_cpp()
static void ce103_hw4_cs_dll.Class2.ce103_hex2bin_cpp (string fiHex, int fiHexLen, byte[] foBin)
Referenced by ce103_hw4_cs_dll.Class2.ce103_hex2bin_cs_imported().
ce103_hex2bin_cs_imported()
void ce103_hw4_cs_dll.Class2.ce103_hex2bin_cs_imported (string fiHex, int fiHexLen, byte[] foBin) inline
References ce103_hw4_cs_dll.Class2.ce103_hex2bin_cpp(), fiHexLen, and foBin.
Referenced by ce103_hw4_test.UnitTest1.ce103_hex2bin_imported_test1(), ce103_hw4_test.UnitTest1.ce103_hex2bin_imported_test2(), ce103_hw4_test.UnitTest1.ce103_hex2bin_imported_test3(), ce103_hw4_test.UnitTest1.ce103_hex2bin_importedcppcs_test1(), ce103_hw4_test.UnitTest1.ce103_hex2bin_importedcppcs_test2(), and ce103_hw4_test.UnitTest1.ce103_hex2bin_importedcppcs_test3().
ce103_strcat_cpp()
static IntPtr ce103_hw4_cs_dll.Class2.ce103_strcat_cpp (char[] fiDest, char[] fiSrc)
Referenced by ce103_hw4_cs_dll.Class2.ce103_strcat_cs_imported().
ce103_strcat_cs_imported()
string ce103_hw4_cs_dll.Class2.ce103_strcat_cs_imported (string fiDest, string fiSrc) inline
References ce103_hw4_cs_dll.Class2.ce103_strcat_cpp(), fiSrc, and ce103_hw4_cs_dll.Class2.PtrToStringUtf8().
Referenced by ce103_hw4_test.UnitTest1.ce103_strcat_cs_imported_test_1(), ce103_hw4_test.UnitTest1.ce103_strcat_cs_imported_test_2(), ce103_hw4_test.UnitTest1.ce103_strcat_cs_imported_test_3(), ce103_hw4_test.UnitTest1.ce103_strcat_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcat_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strcat_importedcppcs_test_3().
ce103_strcmp_cpp()
static int ce103_hw4_cs_dll.Class2.ce103_strcmp_cpp (string fiLhs, string fiRhs)
Referenced by ce103_hw4_cs_dll.Class2.ce103_strcmp_cs_imported().
ce103_strcmp_cs_imported()
int ce103_hw4_cs_dll.Class2.ce103_strcmp_cs_imported (string fiLhs, string fiRhs) inline
References ce103_hw4_cs_dll.Class2.ce103_strcmp_cpp(), and fiRhs.
Referenced by ce103_hw4_test.UnitTest1.ce103_strcmp_cs_imported_test_1(), ce103_hw4_test.UnitTest1.ce103_strcmp_cs_imported_test_2(), ce103_hw4_test.UnitTest1.ce103_strcmp_cs_imported_test_3(), ce103_hw4_test.UnitTest1.ce103_strcmp_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcmp_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strcmp_importedcppcs_test_3().
ce103_strcpy_cpp()
static IntPtr ce103_hw4_cs_dll.Class2.ce103_strcpy_cpp (char[] foDestination, char[] fiSource)
Referenced by ce103_hw4_cs_dll.Class2.ce103_strcpy_cs_imported().
ce103_strcpy_cs_imported()
string ce103_hw4_cs_dll.Class2.ce103_strcpy_cs_imported (string foDestination, string fiSource) inline
References ce103_hw4_cs_dll.Class2.ce103_strcpy_cpp(), fiSource, and ce103_hw4_cs_dll.Class2.PtrToStringUtf8().
Referenced by ce103_hw4_test.UnitTest1.ce103_strcpy_cs_imported_test_1(), ce103_hw4_test.UnitTest1.ce103_strcpy_cs_imported_test_2(), ce103_hw4_test.UnitTest1.ce103_strcpy_cs_imported_test_3(), ce103_hw4_test.UnitTest1.ce103_strcpy_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcpy_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strcpy_importedcppcs_test_3().
ce103_strlen_cpp()
static int ce103_hw4_cs_dll.Class2.ce103_strlen_cpp (string fiStr)
Referenced by ce103_hw4_cs_dll.Class2.ce103_strlen_cs_imported().
ce103_strlen_cs_imported()
int ce103_hw4_cs_dll.Class2.ce103_strlen_cs_imported (string fiStr) inline
References ce103_hw4_cs_dll.Class2.ce103_strlen_cpp().
Referenced by ce103_hw4_test.UnitTest1.ce103_strlen_cs_imported_test_1(), ce103_hw4_test.UnitTest1.ce103_strlen_cs_imported_test_2(), ce103_hw4_test.UnitTest1.ce103_strlen_cs_imported_test_3(), ce103_hw4_test.UnitTest1.ce103_strlen_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strlen_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strlen_importedcppcs_test_3().
ce103_strrev_cpp()
static IntPtr ce103_hw4_cs_dll.Class2.ce103_strrev_cpp (char[] fiStr)
Referenced by ce103_hw4_cs_dll.Class2.ce103_strrev_cs_imported().
ce103_strrev_cs_imported()
string ce103_hw4_cs_dll.Class2.ce103_strrev_cs_imported (string fiStr) inline
References ce103_hw4_cs_dll.Class2.ce103_strrev_cpp(), and ce103_hw4_cs_dll.Class2.PtrToStringUtf8().
Referenced by ce103_hw4_test.UnitTest1.ce103_strrev_cs_imported_test_1(), ce103_hw4_test.UnitTest1.ce103_strrev_cs_imported_test_2(), ce103_hw4_test.UnitTest1.ce103_strrev_cs_imported_test_3(), ce103_hw4_test.UnitTest1.ce103_strrev_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strrev_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strrev_importedcppcs_test_3().
PtrToStringUtf8()
static string ce103_hw4_cs_dll.Class2.PtrToStringUtf8 (IntPtr tr) inline static private
Referenced by ce103_hw4_cs_dll.Class2.ce103_strcat_cs_imported(), ce103_hw4_cs_dll.Class2.ce103_strcpy_cs_imported(), and ce103_hw4_cs_dll.Class2.ce103_strrev_cs_imported().
The documentation for this class was generated from the following file:
C:/Users/Ramazan Serhat UYGUN/Desktop/a/ce103-hw4-haluk-kurtulus/ce103-hw4-cs-dll/Class2.cs