CE103 Algorithms and Programming I HW4: ce103_hw4_cs_dll.Class1 Class Reference
ce103_hw4_cs_dll.Class1 Class Reference
Public Member Functions
fibonacciNumber (ce103_fibonacciNumber_cs)
Fibonacci Number Calculator
Calculates the fibonacci number in the given index and return as output
Parameters
[in] fiIndex [int] index of fibonacci number in the serie
Return values
[
b int] calculated fibonacci number
int ce103_fibonacciNumber_cs (int fiIndex)
strrev (ce103_strrev_cs)
Reverse String
Reverse given string
Parameters
[in] fiStr [string] The given string which is needed to be reversed.
Return values
[
b string] This function returns the string after reversing the given string
string ce103_strrev_cs (string fiStr)
strlen (ce103_strlen_cs)
Get string length
Returns the length of the C# string str.
Parameters
[in] fiStr [string] the null-terminated byte string to be examined
Return values
[
b int] The length of the null-terminated byte string str.
int ce103_strlen_cs (string fiStr)
strcat (ce103_strcat_cs)
Concatenate strings
In this function, we combine 2 randomly entered strings. We give one of our strings "fiDest" and the other "fiSrc", that is, a random string. The sum of these strings gives us the combined return value of the strings.
Parameters
[in] fiDest [string] the null-terminated byte string to append to
[in] fiSrc [string] the null-terminated byte string to copy from
Return values
[
b string] returns a copy of dest
string ce103_strcat_cs (string fiDest, string fiSrc)
strcmp (ce103_strcmp_cs)
Compare two strings
Compares two null-terminated byte strings lexicographically.
Parameters
[in] fiLhs [string] the null-terminated byte strings to compare
[in] fiRhs [string] the null-terminated byte strings to compare
Return values
[
b int] Negative value if lhs appears before rhs in lexicographical order. Zero if lhs and rhs compare equal. Positive value if lhs appears after rhs in lexicographical order.
int ce103_strcmp_cs (string fiLhs, string fiRhs)
strcpy (ce103_strcpy_cs)
Copy string
Copies the C# string pointed by source into the array pointed by destination, including the terminating null character (and stopping at that point).
Parameters
[out] foDestination [string] the destination array where the content is to be copied.
[in] fiSource [string] C string to be copied.
Return values
[
b string] returns a copy of dest
string ce103_strcpy_cs (string foDestination, string fiSource)
bin2hex (ce103_bin2hex_cs)
Binary to Hexadecimal Conversion
Unpacks alpha numeric value, Example: 0x12 0x34 = "1234".
Parameters
[in] fiBin [byte[]] Binary data to be converted.
[in] fiBinLen [int] Binary data length.
[out] foHex [char[]] Convertion result as ascii. Doubles the binary length.
void ce103_bin2hex_cs (byte[] fiBin, int fiBinlen, char[] foHex)
hex2bin (ce103_hex2bin_cs)
Hexadecimal string to byte array Conversion
Convert hex string to byte array
Parameters
[in] fiHex [string] Ascii hex string.
[in] fiHexLen [int] Ascii data length.
[out] foBin [byte[]] Convertion result as binary.
void ce103_hex2bin_cs (string fiHex, int fiHexLen, byte[] foBin)
Member Function Documentation
ce103_bin2hex_cs()
void ce103_hw4_cs_dll.Class1.ce103_bin2hex_cs (byte[] fiBin, int fiBinlen, char[] foHex) inline
References foHex.
Referenced by ce103_hw4_test.UnitTest1.ce103_bin2hex_cs_test1(), ce103_hw4_test.UnitTest1.ce103_bin2hex_cs_test2(), ce103_hw4_test.UnitTest1.ce103_bin2hex_cs_test3(), ce103_hw4_test.UnitTest1.ce103_bin2hex_importedcppcs_test1(), ce103_hw4_test.UnitTest1.ce103_bin2hex_importedcppcs_test2(), and ce103_hw4_test.UnitTest1.ce103_bin2hex_importedcppcs_test3().
ce103_fibonacciNumber_cs()
int ce103_hw4_cs_dll.Class1.ce103_fibonacciNumber_cs (int fiIndex) inline
Referenced by ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_cs_test_1(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_cs_test_2(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_cs_test_3(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_fibonacciNumber_importedcppcs_test_3().
ce103_hex2bin_cs()
void ce103_hw4_cs_dll.Class1.ce103_hex2bin_cs (string fiHex, int fiHexLen, byte[] foBin) inline
References fiHexLen, and foBin.
Referenced by ce103_hw4_test.UnitTest1.ce103_hex2bin_cs_test1(), ce103_hw4_test.UnitTest1.ce103_hex2bin_cs_test2(), ce103_hw4_test.UnitTest1.ce103_hex2bin_cs_test3(), ce103_hw4_test.UnitTest1.ce103_hex2bin_importedcppcs_test1(), ce103_hw4_test.UnitTest1.ce103_hex2bin_importedcppcs_test2(), and ce103_hw4_test.UnitTest1.ce103_hex2bin_importedcppcs_test3().
ce103_strcat_cs()
string ce103_hw4_cs_dll.Class1.ce103_strcat_cs (string fiDest, string fiSrc) inline
References fiSrc.
Referenced by ce103_hw4_test.UnitTest1.ce103_strcat_cs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcat_cs_test_2(), ce103_hw4_test.UnitTest1.ce103_strcat_cs_test_3(), ce103_hw4_test.UnitTest1.ce103_strcat_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcat_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strcat_importedcppcs_test_3().
ce103_strcmp_cs()
int ce103_hw4_cs_dll.Class1.ce103_strcmp_cs (string fiLhs, string fiRhs) inline
References ce103_hw4_cs_dll.Class1.ce103_strlen_cs(), and fiRhs.
Referenced by ce103_hw4_test.UnitTest1.ce103_strcmp_cs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcmp_cs_test_2(), ce103_hw4_test.UnitTest1.ce103_strcmp_cs_test_3(), ce103_hw4_test.UnitTest1.ce103_strcmp_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcmp_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strcmp_importedcppcs_test_3().
ce103_strcpy_cs()
string ce103_hw4_cs_dll.Class1.ce103_strcpy_cs (string foDestination, string fiSource) inline
References fiSource.
Referenced by ce103_hw4_test.UnitTest1.ce103_strcpy_cs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcpy_cs_test_2(), ce103_hw4_test.UnitTest1.ce103_strcpy_cs_test_3(), ce103_hw4_test.UnitTest1.ce103_strcpy_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strcpy_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strcpy_importedcppcs_test_3().
ce103_strlen_cs()
int ce103_hw4_cs_dll.Class1.ce103_strlen_cs (string fiStr) inline
Referenced by ce103_hw4_cs_dll.Class1.ce103_strcmp_cs(), ce103_hw4_test.UnitTest1.ce103_strlen_cs_test_1(), ce103_hw4_test.UnitTest1.ce103_strlen_cs_test_2(), ce103_hw4_test.UnitTest1.ce103_strlen_cs_test_3(), ce103_hw4_test.UnitTest1.ce103_strlen_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strlen_importedcppcs_test_2(), ce103_hw4_test.UnitTest1.ce103_strlen_importedcppcs_test_3(), and ce103_hw4_cs_dll.Class1.ce103_strrev_cs().
ce103_strrev_cs()
string ce103_hw4_cs_dll.Class1.ce103_strrev_cs (string fiStr) inline
References ce103_hw4_cs_dll.Class1.ce103_strlen_cs().
Referenced by ce103_hw4_test.UnitTest1.ce103_strrev_cs_test_1(), ce103_hw4_test.UnitTest1.ce103_strrev_cs_test_2(), ce103_hw4_test.UnitTest1.ce103_strrev_cs_test_3(), ce103_hw4_test.UnitTest1.ce103_strrev_importedcppcs_test_1(), ce103_hw4_test.UnitTest1.ce103_strrev_importedcppcs_test_2(), and ce103_hw4_test.UnitTest1.ce103_strrev_importedcppcs_test_3().
The documentation for this class was generated from the following file:
C:/Users/Ramazan Serhat UYGUN/Desktop/a/ce103-hw4-haluk-kurtulus/ce103-hw4-cs-dll/Class1.cs